#!/usr/bin/env bash

cd Analyser
rm -rf cache

mkdir -p ../../.tmp
MITM_FILE="$(mktemp ../../.tmp/mitmlog.XXXXXXXXX)"
MITM_PORT=$((((RANDOM<<15)|RANDOM) % 63001 + 2000 ))

echo "" > "${MITM_FILE}"

if [[ "$(uname)" == "Darwin" ]]; then
    script -q /dev/null mitmdump --ssl-insecure -p "${MITM_PORT}" -s "node_modules/jalangi2/scripts/proxy.py" --set args="--inlineIID --inlineSource --analysis bin/bundle.js" &> "${MITM_FILE}" &
else
    stdbuf -oL -eL mitmdump --ssl-insecure -p "${MITM_PORT}" -s "node_modules/jalangi2/scripts/proxy.py" --set args="--inlineIID --inlineSource --analysis bin/bundle.js" &> "${MITM_FILE}" &
fi

MITM_PID="$!"

while true;
do

	#Test for error 
	if grep -q "Error" "${MITM_FILE}"; then
		echo "Error in mitmproxy"
		cat "${MITM_FILE}"
		unset MITM_PID;
		unset MITM_FILE;
		break;
	fi

	if grep -q "listening at" "${MITM_FILE}"; then
		echo "Proxy listening on port ${MITM_PORT}"
		break;
	fi

done 

cd ..
